version: '3.7'

services:
  kafka.webapi.producer:
    image: ${DOCKER_REGISTRY-}kafkawebapiproducer
    build:
      context: .
      dockerfile: Kafka.Webapi.Producer/Dockerfile
      
  kafka.consumer:
    image: ${DOCKER_REGISTRY-}kafkaconsumer
    build:
      context: .
      dockerfile: Kafka.Consumer/Dockerfile

